version: '3'

services:
  hospital-master:
    image: bitnami/postgresql-repmgr:latest
    environment:
      POSTGRESQL_POSTGRES_PASSWORD: BUGRIENKO_216
      POSTGRESQL_USERNAME: BUGRIENKO_216
      POSTGRESQL_PASSWORD: BUGRIENKO_216
      POSTGRESQL_DATABASE: BUGRIENKO_216
      REPMGR_PASSWORD: repmgrpassword
      REPMGR_PRIMARY_HOST: hospital-master
      REPMGR_PARTNER_NODES: hospital-master,hospital-slave
      REPMGR_NODE_NAME: node-5
      REPMGR_NODE_NETWORK_NAME: hospital-master
    ports:
      - "5436:5432"
    volumes:
      - ./sql/hospital:/docker-entrypoint-initdb.d
      - hospital_master_data:/bitnami/postgresql

  hospital-slave:
    image: bitnami/postgresql-repmgr:latest
    environment:
      POSTGRESQL_POSTGRES_PASSWORD: adminpassword
      POSTGRESQL_USERNAME: customuser
      POSTGRESQL_PASSWORD: custompassword
      POSTGRESQL_DATABASE: customdatabase
      REPMGR_PASSWORD: repmgrpassword
      REPMGR_PRIMARY_HOST: hospital-master
      REPMGR_PARTNER_NODES: hospital-master,hospital-slave
      REPMGR_NODE_NAME: node-6
      REPMGR_NODE_NETWORK_NAME: hospital-slave
    ports:
      - "5437:5432"
    depends_on:
      - hospital-master
    volumes:
      - hospital_slave_data:/bitnami/postgresql

volumes:
  hospital_master_data:
    driver: local
  hospital_slave_data:
    driver: local
