version: '3'

services:
  library-master:
    image: bitnami/postgresql-repmgr:latest
    environment:
      POSTGRESQL_POSTGRES_PASSWORD: BUGRIENKO_216
      POSTGRESQL_USERNAME: BUGRIENKO_216
      POSTGRESQL_PASSWORD: BUGRIENKO_216
      POSTGRESQL_DATABASE: BUGRIENKO_216
      REPMGR_PASSWORD: repmgrpassword
      REPMGR_PRIMARY_HOST: library-master
      REPMGR_PARTNER_NODES: library-master,library-slave
      REPMGR_NODE_NAME: node-3
      REPMGR_NODE_NETWORK_NAME: library-master
    ports:
      - "5432:5432"
    volumes:
      - ./sql/library:/docker-entrypoint-initdb.d
      - library_master_data:/bitnami/postgresql

  library-slave:
    image: bitnami/postgresql-repmgr:latest
    environment:
      POSTGRESQL_POSTGRES_PASSWORD: adminpassword
      POSTGRESQL_USERNAME: customuser
      POSTGRESQL_PASSWORD: custompassword
      POSTGRESQL_DATABASE: customdatabase
      REPMGR_PASSWORD: repmgrpassword
      REPMGR_PRIMARY_HOST: library-master
      REPMGR_PARTNER_NODES: library-master,library-slave
      REPMGR_NODE_NAME: node-4
      REPMGR_NODE_NETWORK_NAME: library-slave
    ports:
      - "5433:5432"
    depends_on:
      - library-master
    volumes:
      - library_slave_data:/bitnami/postgresql

volumes:
  library_master_data:
    driver: local
  library_slave_data:
    driver: local
