version: '3'

services:
  trains-master:
    image: bitnami/postgresql-repmgr:latest
    environment:
      POSTGRESQL_POSTGRES_PASSWORD: BUGRIENKO_216
      POSTGRESQL_USERNAME: BUGRIENKO_216
      POSTGRESQL_PASSWORD: BUGRIENKO_216
      POSTGRESQL_DATABASE: BUGRIENKO_216
      REPMGR_PASSWORD: repmgrpassword
      REPMGR_PRIMARY_HOST: trains-master
      REPMGR_PARTNER_NODES: trains-master,trains-slave
      REPMGR_NODE_NAME: node-1
      REPMGR_NODE_NETWORK_NAME: trains-master
    ports:
      - "5434:5432"
    volumes:
      - ./sql/trains:/docker-entrypoint-initdb.d
      - trains_master_data:/bitnami/postgresql

  trains-slave:
    image: bitnami/postgresql-repmgr:latest
    environment:
      POSTGRESQL_POSTGRES_PASSWORD: adminpassword
      POSTGRESQL_USERNAME: customuser
      POSTGRESQL_PASSWORD: custompassword
      POSTGRESQL_DATABASE: customdatabase
      REPMGR_PASSWORD: repmgrpassword
      REPMGR_PRIMARY_HOST: trains-master
      REPMGR_PARTNER_NODES: trains-master,trains-slave
      REPMGR_NODE_NAME: node-2
      REPMGR_NODE_NETWORK_NAME: trains-slave
    ports:
      - "5435:5432"
    depends_on:
      - trains-master
    volumes:
      - trains_slave_data:/bitnami/postgresql

volumes:
  trains_master_data:
    driver: local
  trains_slave_data:
    driver: local
